package adventofcode2016

import zio.*

import java.io.IOException
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

/** Solves Day 05 of Advent of Code 2016.
  *
  * This object contains methods to calculate two different passwords based on a given Door ID by hashing operations.
  */
object Day05ZIO extends ZIOAppDefault:

  /** Creates a new MD5 MessageDigest instance for thread safety.
    */
  private def newMd5(): MessageDigest = MessageDigest.getInstance("MD5")

  /** Calculates the MD5 hash of a given string.
    *
    * @param s
    *   The input string.
    * @return
    *   The MD5 hash of the string as a 32-character hexadecimal string.
    */
  private def md5(s: String): UIO[String] =
    ZIO.succeed:
      val md = newMd5()
      val hashBytes = md.digest(s.getBytes(StandardCharsets.UTF_8))
      hashBytes.map("%02x".format(_)).mkString

  /** Calculates the first password for Day 05.
    *
    * The password is an 8-character string formed by taking the 6th character of MD5 hashes that start with five zeroes
    * ("00000"). Hashes are generated by appending sequential integers (starting from 0) to the door ID.
    *
    * This implementation uses ZIO's parallel processing power in batches (forking fibers, then joining them).
    *
    * @param doorID
    *   The door ID string.
    * @return
    *   The calculated 8-character password.
    */
  def calculatePassword(doorID: String): UIO[String] =

    val batchSize = 1024

    def batchFindChars(from: Long): UIO[Array[Char]] =
      ZIO
        .foreach(from until from + batchSize)(n => md5(doorID + n).fork)
        .flatMap(f => Fiber.collectAll(f).join)
        .map(_.filter(_.startsWith("00000")).map(_.charAt(5)).toArray)

    val countingTuple = ZIO.iterate((0, Array.empty[Char]))(_._2.length < 8):
      case (n, pwd) =>
        for
          moreChars <- batchFindChars(n)
          chars = pwd ++ moreChars
        yield (n + batchSize, chars)

    countingTuple.map(_._2).map(_.take(8)).map(_.mkString)

  /** Calculates the second password for Day 05.
    *
    * The password is an 8-character string where each character is placed at a specific position. The 6th character of
    * an MD5 hash (that starts with five zeroes) indicates the position (0-7), and the 7th character indicates the
    * character for that position. Positions can only be filled once.
    *
    * @param doorID
    *   The door ID string.
    * @return
    *   The calculated 8-character password.
    */
  def calculateSecondPassword(doorID: String): UIO[String] =
    val batchSize = 1024

    def batchFindChars(from: Long, seenRef: Ref[Set[Int]]): UIO[Array[(Int, Char)]] = {
      val (start, end) = (from, from + batchSize)
      for
        potentialEntries <- ZIO
          .foreach(start until end)(n => md5(doorID + n).fork)
          .flatMap(f => Fiber.collectAll(f).join)
          .map: hashes =>
            hashes
              .filter(_.startsWith("00000"))
              .filter(h => h.charAt(5) >= '0' && h.charAt(5) <= '7')
              .map: h =>
                (h.charAt(5) - '0', h.charAt(6))
              .map: entry =>
                seenRef.modify: seen =>
                  if seen.contains(entry._1) then (None, seen)
                  else (Some(entry), seen + entry._1)
        collectedEntries <- ZIO.collectAll(potentialEntries)
        actualEntries = collectedEntries.collect:
          case Some(char) => char
      yield actualEntries.toArray
    }

    for
      seenRef <- Ref.make(Set.empty[Int])

      countingTuple = ZIO.iterate((0, Array.empty[(Int, Char)]))(_._2.length < 8):
        case (n, currentEntries) =>
          for
            newEntries <- batchFindChars(n, seenRef)
            entries = currentEntries ++ newEntries
          yield (n + batchSize, entries)

      pwd <- countingTuple
        .map:
          case (_, entries) =>
            val entriesMap = entries.toMap
            (0 to 7).map(entriesMap(_)).mkString
    yield pwd

  /** The main entry point for the Day 05 application.
    *
    * Calculates and prints both the first and second passwords for the predefined door ID "ugkcyxxp".
    */
  def run: ZIO[ZIOAppArgs & Scope, IOException, Unit] =
    println("Day 05")
    val doorID = "ugkcyxxp"
    for
      password <- calculatePassword(doorID)
      _ <- Console.printLine(s"password: $password")
      secondPassword <- calculateSecondPassword(doorID)
      _ <- Console.printLine(s"second password: $secondPassword")
    yield ()
