package adventofcode2016

import zio.*

import java.io.IOException
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

/** Solves Day 05 of Advent of Code 2016.
  *
  * This object contains methods to calculate two different passwords based on a given Door ID by hashing operations.
  */
object Day05ZIO extends ZIOAppDefault:

  /** Creates a new MD5 MessageDigest instance for thread safety.
    */
  private def newMd5(): MessageDigest = MessageDigest.getInstance("MD5")

  /** Calculates the MD5 hash of a given string.
    *
    * @param s
    *   The input string.
    * @return
    *   The MD5 hash of the string as a 32-character hexadecimal string.
    */
  private def md5(s: String): UIO[String] =
    ZIO.succeed:
      val md = newMd5()
      val hashBytes = md.digest(s.getBytes(StandardCharsets.UTF_8))
      hashBytes.map("%02x".format(_)).mkString

  /** Calculates the first password for Day 05.
    *
    * The password is an 8-character string formed by taking the 6th character of MD5 hashes that start with five zeroes
    * ("00000"). Hashes are generated by appending sequential integers (starting from 0) to the door ID.
    *
    * This implementation uses ZIO's parallel processing power in batches (forking fibers, then joining them).
    *
    * @param doorID
    *   The door ID string.
    * @return
    *   The calculated 8-character password.
    */
  def calculatePassword(doorID: String): UIO[String] =

    val batchSize = 1024

    def batchFindChars(from: Long): UIO[Array[Char]] =
      ZIO
        .foreach(from until from + batchSize)(n => md5(doorID + n).fork)
        .flatMap(f => Fiber.collectAll(f).join)
        .map(_.filter(_.startsWith("00000")).map(_.charAt(5)).toArray)

    val countingTuple = ZIO.iterate((0, Array.empty[Char]))(_._2.length <= 8):
      case (n, pwd) =>
        for
          moreChars <- batchFindChars(n)
          chars = pwd ++ moreChars
        yield (n + batchSize, chars)

    countingTuple.map(_._2).map(_.take(8)).map(_.mkString)

  /** The main entry point for the Day 05 application.
    *
    * Calculates and prints both the first and second passwords for the predefined door ID "ugkcyxxp".
    */
  def run: ZIO[ZIOAppArgs & Scope, IOException, Unit] =
    println("Day 05")
    val doorID = "ugkcyxxp"
    for
      password <- calculatePassword(doorID)
      _ <- Console.printLine(s"password: $password")
    yield ()
