package adventofcode2016

import zio.*
import zio.stream.ZStream

import java.io.IOException
import java.lang
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

/** Solves Day 05 of Advent of Code 2016.
  *
  * This object contains methods to calculate two different passwords based on a given Door ID by hashing operations.
  */
object Day05ZIO extends ZIOAppDefault:

  /** Creates a new MD5 MessageDigest instance for thread safety.
    */
  private def newMd5(): MessageDigest = MessageDigest.getInstance("MD5")

  /** Calculates the MD5 hash of a given string.
    *
    * @param s
    *   The input string.
    * @return
    *   The MD5 hash of the string as a 32-character hexadecimal string.
    */
  private def md5(s: String): UIO[String] =
    ZIO.succeed:
      val md = newMd5()
      val hashBytes = md.digest(s.getBytes(StandardCharsets.UTF_8))
      hashBytes.map("%02x".format(_)).mkString

  /** Calculates the first password for Day 05.
    *
    * The password is an 8-character string formed by taking the 6th character of MD5 hashes that start with five zeroes
    * ("00000"). Hashes are generated by appending sequential integers (starting from 0) to the door ID.
    *
    * This implementation uses ZIO's parallel processing power in batches (forking fibers, then joining them).
    *
    * @param doorID
    *   The door ID string.
    * @return
    *   The calculated 8-character password.
    */
  def calculatePassword(doorID: String): UIO[String] =

    val batchSize = 1024

    def batchFindChars(from: Long): UIO[Array[Char]] =
      ZIO
        .foreach(from until from + batchSize)(n => md5(doorID + n).fork)
        .flatMap(f => Fiber.collectAll(f).join)
        .map(_.filter(_.startsWith("00000")).map(_.charAt(5)).toArray)

    val countingTuple = ZIO.iterate((0, Array.empty[Char]))(_._2.length <= 8):
      case (n, pwd) =>
        for
          moreChars <- batchFindChars(n)
          chars = pwd ++ moreChars
        yield (n + batchSize, chars)

    countingTuple.map(_._2).map(_.take(8)).map(_.mkString)

  /** Calculates the second password for Day 05.
    *
    * The password is an 8-character string where each character is placed at a specific position. The 6th character of
    * an MD5 hash (that starts with five zeroes) indicates the position (0-7), and the 7th character indicates the
    * character for that position. Positions can only be filled once.
    *
    * @param doorID
    *   The door ID string.
    * @return
    *   The calculated 8-character password.
    */
  def calculateSecondPassword(doorID: String): UIO[String] =
    ZStream
      .iterate(0L)(_ + 1)
      .mapZIOPar(8): n =>
        md5(doorID + n)
      .filter(_.startsWith("00000"))
      .debug
      .map: hash =>
        val pos = hash.charAt(5)
        val char = hash.charAt(6)
        (pos, char)
      .filter: (pos, _) =>
        pos >= '0' && pos <= '7'
      .map: (pos, char) =>
        (pos - '0', char)
      .scan((Set.empty[Int], Map.empty[Int, Char])):
        case ((seen, password), (pos, char)) =>
          if seen.contains(pos) then (seen, password)
          else (seen + pos, password + (pos -> char))
      .takeWhile(_._1.size < 8)
      .runLast
      .map:
        case Some((_, passwordMap)) =>
          (0 until 8).map(passwordMap).mkString
        case None =>
          "" // Should never happen
  /** The main entry point for the Day 05 application.
    *
    * Calculates and prints both the first and second passwords for the predefined door ID "ugkcyxxp".
    */
  def run: ZIO[ZIOAppArgs & Scope, IOException, Unit] =
    println("Day 05")
    val doorID = "ugkcyxxp"
    for
      password <- calculatePassword(doorID)
      _ <- Console.printLine(s"password: $password")
    yield ()
