package adventofcode2016

import scala.annotation.tailrec
import scala.collection.immutable.Queue

/**
 * A solution to Day 13 of Advent of Code 2016.
 *
 * This program solves two parts of a puzzle involving navigating a maze generated by a specific
 * formula, using a breadth-first search (BFS) algorithm.
 */
object Day13:

  /**
   * Represents a location in the 2D maze with (x, y) coordinates.
   *
   * @param x The x-coordinate.
   * @param y The y-coordinate.
   */
  private case class Coordinates(x: Int, y: Int):
    /**
     * Determines if the coordinates represent an open space based on the favourite number.
     *
     * The algorithm for determining a space is:
     * 1. Calculate `n = x*x + 3*x + 2*x*y + y + y*y + favouriteNumber`.
     * 2. Convert `n` to its binary representation.
     * 3. Count the number of '1' bits.
     * 4. If the count is even, the location is a space.
     *
     * @param number The favourite number used for maze generation.
     * @return `true` if the location is a space, `false` otherwise.
     */
    def isSpace(number: Int): Boolean =
      val n = number + x * x + 3 * x + 2 * x * y + y + y * y
      val nBits = n.toBinaryString.count(_ == '1')
      nBits % 2 == 0

  /**
   * Finds the shortest path in terms of steps from an origin to a destination.
   *
   * @param origin          The starting coordinate.
   * @param destination     The target coordinate.
   * @param favouriteNumber The favourite number for maze generation.
   * @return A list of coordinates representing the shortest path.
   */
  private def findSteps(origin: Coordinates, destination: Coordinates, favouriteNumber: Int): List[Coordinates] =

    def reconstructPath(parents: Map[Coordinates, Coordinates], target: Coordinates): List[Coordinates] =
      @tailrec
      def loop(current: Coordinates, acc: List[Coordinates]): List[Coordinates] =
        parents.get(current) match
          case Some(parent) => loop(parent, current :: acc)
          case None => current :: acc

      loop(target, Nil)

    @tailrec
    def loop(parents: Map[Coordinates, Coordinates], seen: Set[Coordinates], queue: Queue[Coordinates]): Map[Coordinates, Coordinates] =
      if queue.isEmpty then parents
      else
        val (current, reducedQueue) = queue.dequeue
        if current == destination then parents
        else
          val candidates = Set(
            Coordinates(current.x - 1, current.y),
            Coordinates(current.x + 1, current.y),
            Coordinates(current.x, current.y - 1),
            Coordinates(current.x, current.y + 1),
          ).filterNot(c => c.x < 0 || c.y < 0).diff(seen)
          val (validCandidates, walls) = candidates.partition(_.isSpace(favouriteNumber))
          val newSeen = seen ++ walls + current
          val newQueue = reducedQueue.enqueueAll(validCandidates)
          val newPredecessors = parents ++ validCandidates.map(_ -> current)
          loop(newPredecessors, newSeen, newQueue)

    val predecessorMap = loop(Map.empty, Set(origin), Queue(origin))
    reconstructPath(predecessorMap, destination)

  /**
   * Finds all unique locations reachable from the origin within a maximum number of steps.
   * This is a breadth-first search (BFS) that tracks the number of steps taken.
   *
   * @param origin          The starting coordinate.
   * @param favouriteNumber The favourite number for maze generation.
   * @param maxSteps        The maximum number of steps allowed.
   * @return A set of unique `Coordinates` that are reachable.
   */
  private def visitedLocations(origin: Coordinates, favouriteNumber: Int, maxSteps: Int): Set[Coordinates] =
    @tailrec
    def loop(seen: Set[Coordinates], queue: Queue[(Coordinates, Int)]): Set[Coordinates] =
      if queue.isEmpty then seen
      else
        val ((current, steps), reducedQueue) = queue.dequeue
        if steps >= maxSteps then seen
        else
          val candidates = Set(
            Coordinates(current.x - 1, current.y),
            Coordinates(current.x + 1, current.y),
            Coordinates(current.x, current.y - 1),
            Coordinates(current.x, current.y + 1),
          ).filterNot(c => c.x < 0 || c.y < 0).filter(_.isSpace(favouriteNumber))

          val newCandidates = candidates.diff(seen)
          val newQueue = reducedQueue.enqueueAll(newCandidates.map(_ -> (steps + 1)))
          loop(seen ++ newCandidates, newQueue)

    val initialQueue = Queue(origin -> 0)
    val initialSeen = Set(origin)
    loop(initialSeen, initialQueue)


  /**
   * Main method to run the solution for Day 13.
   * It calculates and prints the results for both Part 1 and Part 2 of the puzzle.
   */
  @main
  def day13(): Unit =
    val favouriteNumber = 1362

    val steps = findSteps(Coordinates(1, 1), Coordinates(31, 39), favouriteNumber)
    println(s"Part 1: the minimum path length is ${steps.length - 1}")

    val maxSteps = 50

    val locations = visitedLocations(Coordinates(1, 1), favouriteNumber, maxSteps)
    println(s"Part 2: visitable locations within $maxSteps steps: ${locations.size}")